//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 09:26:38 AM IST 
//


package com.intraedge.student.jaxb2beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.intraedge.student.jaxb2beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.intraedge.student.jaxb2beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegisterStudentRequest }
     * 
     */
    public RegisterStudentRequest createRegisterStudentRequest() {
        return new RegisterStudentRequest();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link RegisterStudentResponse }
     * 
     */
    public RegisterStudentResponse createRegisterStudentResponse() {
        return new RegisterStudentResponse();
    }

    /**
     * Create an instance of {@link PhoneNumber }
     * 
     */
    public PhoneNumber createPhoneNumber() {
        return new PhoneNumber();
    }

    /**
     * Create an instance of {@link GetStudentPhoneNumbersRequest }
     * 
     */
    public GetStudentPhoneNumbersRequest createGetStudentPhoneNumbersRequest() {
        return new GetStudentPhoneNumbersRequest();
    }

    /**
     * Create an instance of {@link Student }
     * 
     */
    public Student createStudent() {
        return new Student();
    }

    /**
     * Create an instance of {@link GetStudentPhoneNumbersResponse }
     * 
     */
    public GetStudentPhoneNumbersResponse createGetStudentPhoneNumbersResponse() {
        return new GetStudentPhoneNumbersResponse();
    }

    /**
     * Create an instance of {@link GetStudentAddressRequest }
     * 
     */
    public GetStudentAddressRequest createGetStudentAddressRequest() {
        return new GetStudentAddressRequest();
    }

    /**
     * Create an instance of {@link GetStudentNamesRequest }
     * 
     */
    public GetStudentNamesRequest createGetStudentNamesRequest() {
        return new GetStudentNamesRequest();
    }

    /**
     * Create an instance of {@link GetStudentNamesResponse }
     * 
     */
    public GetStudentNamesResponse createGetStudentNamesResponse() {
        return new GetStudentNamesResponse();
    }

    /**
     * Create an instance of {@link GetStudentAddressResponse }
     * 
     */
    public GetStudentAddressResponse createGetStudentAddressResponse() {
        return new GetStudentAddressResponse();
    }

    /**
     * Create an instance of {@link StudentName }
     * 
     */
    public StudentName createStudentName() {
        return new StudentName();
    }

}
